version: '3'

services:
  web:
    container_name: web
    build:
      context: ./web
      dockerfile: Dockerfile

    volumes:
      - ./web/src:/app/src
      - ./web/public:/app/public
    restart: always
    ports:
      - 3000:3000

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "3010:3010"
    depends_on:
      - delliv-db
    volumes:
      - ./api:/app
  delliv-db:
    container_name: delliv-db
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword
      POSTGRES_DB: delliv-db
    ports:
      - '5432:5432'
